funcionan mis configuraciones hasta TheHive

diff --git a/wazuh/wazuh_managers/wazuh-worker-sts.yaml b/wazuh/wazuh_managers/wazuh-worker-sts.yaml
--- a/wazuh/wazuh_managers/wazuh-worker-sts.yaml
+++ b/wazuh/wazuh_managers/wazuh-worker-sts.yaml
@@ -34,6 +34,20 @@ spec:
               podAffinityTerm:
                 topologyKey: kubernetes.io/hostname
       volumes:
+        - name: custom-scripts #########START MY CONFIG##############
+          configMap:
+            name: custom-w2thive-script
+        - name: custom-scripts-bash
+          configMap:
+            name: custom-w2thive-bash
+        - name: temp-storage      
+          emptyDir: {}            
+        - name: sentinelone-rules 
+          configMap:
+            name: sentinelone-rules-configmap 
+        - name: sentinelone-decoders
+          configMap:
+            name: sentinelone-decoders-configmap   ########ENDS MY CONFIG######               
         - name: config
           configMap:
             name: wazuh-conf
@@ -42,6 +56,77 @@ spec:
             secretName: indexer-certs
       securityContext:
         fsGroup: 101
+      initContainers:
+        - name: init-permissions
+          image: 'wazuh/wazuh-manager:4.9.1'
+          resources:
+            requests:
+              cpu: 50m
+              memory: 128Mi
+            limits:
+              cpu: 100m
+              memory: 256Mi      
+          securityContext:
+            runAsUser: 0
+            runAsGroup: 0                      
+          command: 
+            - 'sh'
+            - '-c'
+            - |
+              echo "Copiando scripts desde ConfigMap a directorio temporal..."
+              cp /temp-config-w2thive/custom-w2thive.py /temp-storage/ || echo "Error copiando custom-w2thive.py"
+              cp /temp-config-w2thive/custom-w2thive /temp-storage/ || echo "Error copiando custom-w2thive"
+
+              echo "Cambiando permisos y propietario en /temp-storage"
+              chmod 750 /temp-storage/custom-w2thive.py /temp-storage/custom-w2thive || echo "Error cambiando permisos"
+              chown root:wazuh /temp-storage/custom-w2thive.py /temp-storage/custom-w2thive || echo "Error cambiando propietario"
+
+              echo "Instalando thehive4py versión en el entorno de Wazuh..."
+              /var/ossec/framework/python/bin/pip3 install thehive4py || echo "Error instalando thehive4py"
+          #    echo "Copiando archivos a /var/ossec/integrations"
+          #    cp /temp-storage/custom-w2thive.py /var/ossec/integrations/ && echo "Copiado custom-w2thive.py" || echo "Error copiando custom-w2thive.py"
+          #    cp /temp-storage/custom-w2thive /var/ossec/integrations/ && echo "Copiado custom-w2thive" || echo "Error copiando custom-w2thive" 
+
+          #    echo "Borrando los archivos originales en /temp-storage"
+          #    rm -f /temp-storage/custom-w2thive.py /temp-storage/custom-w2thive || echo "Error borrando archivos"
+               
+          # echo "Verificando archivos en /temp-storage"
+          # ls -l /temp-storage/custom-w2thive.py /temp-storage/custom-w2thive || echo "Error verificando archivos en /temp-storage"              
+
+          # echo "Moviendo archivos de /temp-storage a /config-thive"
+          # mv /temp-storage/custom-w2thive.py /config-thive/custom-w2thive.py  || echo "Error moviendo custom-w2thive.py a /config-thive"
+          # mv /temp-storage/custom-w2thive /config-thive/custom-w2thive || echo "Error moviendo custom-w2thive a /config-thive"
+
+          # echo "Verificando archivos en /config-thive"
+          # ls -l /config-thive/custom-w2thive.py /config-thive/custom-w2thive || echo "Error verificando archivos en /config-thive"
+              
+          # # Asegúrate de que el directorio existe
+          # echo "Creando directorio /var/ossec/integrations si no existe..."
+          # mkdir -p /var/ossec/integrations || echo "Error creando /var/ossec/integrations"
+              
+          # echo "Verificando existencia de /var/ossec/integrations:"
+          # ls -ld /var/ossec/integrations              
+
+          # echo "Archivos en /temp-storage antes de mover:"
+          # ls -l /temp-storage/
+
+          # echo "Copiando archivos a /var/ossec/integrations"
+          # cp /temp-storage/custom-w2thive.py /var/ossec/integrations/ && echo "Copiado custom-w2thive.py" || echo "Error copiando custom-w2thive.py"
+          # cp /temp-storage/custom-w2thive /var/ossec/integrations/ && echo "Copiado custom-w2thive" || echo "Error copiando custom-w2thive"
+              
+ 
+          volumeMounts:
+            - name: temp-storage
+              mountPath: /temp-storage
+              readOnly: false
+            - name: custom-scripts
+              mountPath: /temp-config-w2thive/custom-w2thive.py
+              subPath: custom-w2thive.py
+              #readOnly: true
+            - name: custom-scripts-bash
+              mountPath: /temp-config-w2thive/custom-w2thive
+              subPath: custom-w2thive
+              #readOnly: true           
       containers:
         - name: wazuh-manager
           image: 'wazuh/wazuh-manager:4.9.1'
@@ -53,6 +138,28 @@ spec:
             capabilities:
               add: ["SYS_CHROOT"]
           volumeMounts:
+            - name: config   #########START MY CONFIG##############
+              mountPath: /etc/filebeat/filebeat.yml 
+              subPath: filebeat.yml  
+            - name: temp-storage
+              mountPath: /temp-storage # Aquí se monta el volumen temporal
+              readOnly: false
+            - name: custom-scripts
+              mountPath: /temp-config-w2thive/custom-w2thive.py
+              subPath: custom-w2thive.py
+              readOnly: true
+            - name: custom-scripts-bash
+              mountPath: /temp-config-w2thive/custom-w2thive
+              subPath: custom-w2thive
+              readOnly: true                                
+            - name: sentinelone-rules
+              mountPath: /var/ossec/etc/rules/sentinelone_rules.xml
+              subPath: sentinelone_rules.xml
+              readOnly: true
+            - name: sentinelone-decoders
+              mountPath: /var/ossec/etc/decoders/sentinelone_decoders.xml
+              subPath: sentinelone_decoders.xml
+              readOnly: true  #######ENDS MY CONFIG###############                      
             - name: config
               mountPath: /wazuh-config-mount/etc/ossec.conf
               subPath: worker.conf
