Download artifacts URLs file to get the deveelopment artifacts files

diff --git a/.github/workflows/local-deployment-test.yml b/.github/workflows/local-deployment-test.yml
--- a/.github/workflows/local-deployment-test.yml
+++ b/.github/workflows/local-deployment-test.yml
@@ -18,8 +18,10 @@ env:
   AWS_REGION: us-west-1
   ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-1.amazonaws.com
   WAZUH_REVISION: latest
+  ARTIFACT_URLS_FILE_TEMP: "/tmp/wazuh-docker/artifact_urls.yml"
 
 jobs:
+
   Local_deployment_test:
     runs-on: ubuntu-24.04
     steps:
@@ -33,6 +35,141 @@ jobs:
         with:
           role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
           aws-region: "${{ env.AWS_REGION }}"
+
+      - name: Get Wazuh version
+        run: |
+            WAZUH_VERSION=$(jq -r '.version' VERSION.json)
+            WAZUH_MAJOR=$(echo "$WAZUH_VERSION" | cut -d '.' -f 1)
+            WAZUH_MINOR=$(echo "$WAZUH_VERSION" | cut -d '.' -f 1-2)
+            ASSISTANT_REVISION=latest
+            INDEXER_COMMIT=latest
+            MANAGER_COMMIT=latest
+            DASHBOARD_COMMIT=latest
+            AGENT_COMMIT=latest
+            echo WAZUH_VERSION=$WAZUH_VERSION >> $GITHUB_ENV
+            echo WAZUH_MAJOR=$WAZUH_MAJOR >> $GITHUB_ENV
+            echo WAZUH_MINOR=$WAZUH_MINOR >> $GITHUB_ENV
+            echo ASSISTANT_REVISION=$ASSISTANT_REVISION >> $GITHUB_ENV
+            echo INDEXER_COMMIT=$INDEXER_COMMIT >> $GITHUB_ENV
+            echo MANAGER_COMMIT=$MANAGER_COMMIT >> $GITHUB_ENV
+            echo DASHBOARD_COMMIT=$DASHBOARD_COMMIT >> $GITHUB_ENV
+            echo AGENT_COMMIT=$AGENT_COMMIT >> $GITHUB_ENV
+
+      - name: Download S3 package URIs file
+        run: |
+          mkdir -p "$(dirname "$ARTIFACT_URLS_FILE_TEMP")"
+
+          # Download the S3 package URIs file
+          S3_BUCKET="${{ secrets.ARTIFACTS_S3_BUCKET }}"
+          S3_KEY="deployment/artifact_urls.yml"
+          aws s3 cp "s3://$S3_BUCKET/$S3_KEY" "$ARTIFACT_URLS_FILE_TEMP" --region ${{ env.AWS_REGION }}
+
+          # Verify the file was downloaded
+          if [ -f "$ARTIFACT_URLS_FILE_TEMP" ]; then
+            echo "S3 package URIs file downloaded successfully."
+          else
+            echo "Failed to download S3 package URIs file." >&2
+            exit 1
+          fi
+
+      - name: Generate the variables file (signing each package URI)
+        run: |
+
+          OUTPUT_FILE="/tmp/wazuh-docker/artifact_urls_processed.yml"
+          PRESIGNED_OUTPUT_FILE="/tmp/wazuh-docker/artifact_urls_presigned.yml"
+
+          mkdir -p "$(dirname "$OUTPUT_FILE")"
+
+          : > "$OUTPUT_FILE"
+          : > "$PRESIGNED_OUTPUT_FILE"
+
+          # Verify if the input file exists
+          if [ ! -f "$ARTIFACT_URLS_FILE_TEMP" ]; then
+            echo "The input file $ARTIFACT_URLS_FILE_TEMP does not exist." >&2
+            exit 1
+          fi
+
+          # Process the file line by line (replacing ocurrences)
+          while IFS= read -r line || [ -n "$line" ]; do
+            # Skip empty lines and comments
+            if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
+              echo "$line" >> "$OUTPUT_FILE"
+              continue
+            fi
+
+            # Replace variables with their actual values
+            line=${line//\$\{\{ vars.AWS_S3_BUCKET_DEV \}\}/${{ vars.AWS_S3_BUCKET_DEV }}}
+            line=${line//\$\{\{ env.MAJOR \}\}/${{ env.WAZUH_MAJOR }}}
+            line=${line//\$\{\{ env.WAZUH_VERSION \}\}/${{ env.WAZUH_VERSION }}}
+
+            # Replace component revisions
+            line=${line//\$\{\{ env.ASSISTANT_REVISION \}\}/${{ env.ASSISTANT_REVISION }}}
+            line=${line//\$\{\{ env.INDEXER_REVISION \}\}/${{ env.INDEXER_COMMIT }}}
+            line=${line//\$\{\{ env.MANAGER_REVISION \}\}/${{ env.MANAGER_COMMIT }}}
+            line=${line//\$\{\{ env.DASHBOARD_REVISION \}\}/${{ env.DASHBOARD_COMMIT }}}
+            line=${line//\$\{\{ env.AGENT_REVISION \}\}/${{ env.AGENT_COMMIT }}}
+
+            # Append the processed line to the output file
+            echo "$line" >> "$OUTPUT_FILE"
+          done < "$ARTIFACT_URLS_FILE_TEMP"
+
+          # Verify the output file
+          if [ -f "$OUTPUT_FILE" ]; then
+            echo "The downloaded file artifact_urls.yml was successfully processed at $OUTPUT_FILE."
+          else
+            echo "Failed to create processed artifact_urls.yml file." >&2
+            exit 1
+          fi
+
+          # Generate the presigned URLs for each package
+          while IFS= read -r line || [ -n "$line" ]; do
+            # Skip empty lines and comments
+            if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
+              echo "$line" >> "$PRESIGNED_OUTPUT_FILE"
+              continue
+            fi
+
+            # Extract both package_name and package_s3_uri from the line
+            if [[ "$line" =~ ^([a-zA-Z0-9_]+):[[:space:]]*\"?s3://([^\"[:space:]]+) ]]; then
+              PACKAGE_NAME="${BASH_REMATCH[1]}"
+              PACKAGE_S3_URI="s3://${BASH_REMATCH[2]}"
+
+              # Check if the object exists in S3
+              BUCKET_NAME=$(echo "$PACKAGE_S3_URI" | cut -d '/' -f 3)
+              OBJ_KEY=$(echo "$PACKAGE_S3_URI" | cut -d '/' -f 4-)
+              if ! aws s3api head-object --bucket "$BUCKET_NAME" --key "$OBJ_KEY" --region us-west-1 > /dev/null 2>&1; then
+                echo "Object $PACKAGE_S3_URI does not exist. Skipping..." >&2
+                continue
+              fi
+
+              # Generate a pre-signed URL for the S3 URI
+              echo "Generating pre-signed URL for $PACKAGE_NAME..."
+              PRESIGNED_URL=$(aws s3 presign "$PACKAGE_S3_URI" --expires-in 43200 --region us-west-1)
+              presigned_url_line="$PACKAGE_NAME: \"$PRESIGNED_URL\""
+
+              # Append the processed line to the output file
+              echo "$presigned_url_line" >> "$PRESIGNED_OUTPUT_FILE"
+            else
+              echo "$line" >> "$PRESIGNED_OUTPUT_FILE"
+
+              echo "Skipping line for presigning (no S3 URI found):"
+              echo "$line"
+            fi
+          done < "$OUTPUT_FILE"
+
+          # Verify the presigned urls file
+          if [ -f "$PRESIGNED_OUTPUT_FILE" ]; then
+            echo "Presigned URLs file created successfully at $PRESIGNED_OUTPUT_FILE."
+          else
+            echo "Failed to create presigned artifact_urls.yml file." >&2
+            exit 1
+          fi
+
+          awk -F':' '!/^#/ && NF>1 {name=$1; val=substr($0,length(name)+3); gsub(/[-.]/,"_",name); print name "=" val}' $PRESIGNED_OUTPUT_FILE > artifacts_env.txt
+
+          set -a
+          source ./artifacts_env.txt
+          set +a
 
       - name: Install pytest
         run: |
@@ -57,23 +194,14 @@ jobs:
       - name: Start Minikube cluster
         run: minikube start --memory=8192 --cpus=4 --network-plugin=cni --cni=calico
 
-      - name: Get Wazuh version
-        run: |
-            WAZUH_VERSION=$(jq -r '.version' VERSION.json)
-            WAZUH_MAJOR=$(echo "$WAZUH_VERSION" | cut -d '.' -f 1)
-            WAZUH_MINOR=$(echo "$WAZUH_VERSION" | cut -d '.' -f 1-2)
-            echo WAZUH_VERSION=$WAZUH_VERSION >> $GITHUB_ENV
-            echo WAZUH_MAJOR=$WAZUH_MAJOR >> $GITHUB_ENV
-            echo WAZUH_MINOR=$WAZUH_MINOR >> $GITHUB_ENV
-
       - name: Replace image registry to ECR
         run: |
-          yq e -i '.spec.template.spec.containers[] |= select(.name == "wazuh-dashboard").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-dashboard:${{ env.WAZUH_VERSION }}"' wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
-          yq e -i '.spec.template.spec.containers[] |= select(.name == "wazuh-indexer").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-indexer:${{ env.WAZUH_VERSION }}"' wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
-          yq e -i '.spec.template.spec.initContainers[] |= select(.name == "init-wazuh-etc").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}"' wazuh/wazuh_managers/wazuh-master-sts.yaml
-          yq e -i '.spec.template.spec.containers[] |= select(.name == "wazuh-manager").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}"' wazuh/wazuh_managers/wazuh-master-sts.yaml
-          yq e -i '.spec.template.spec.initContainers[] |= select(.name == "init-wazuh-etc").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}"' wazuh/wazuh_managers/wazuh-worker-sts.yaml
-          yq e -i '.spec.template.spec.containers[] |= select(.name == "wazuh-manager").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}"' wazuh/wazuh_managers/wazuh-worker-sts.yaml
+          yq e -i '.spec.template.spec.containers[] |= select(.name == "wazuh-dashboard").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-dashboard:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}"' wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
+          yq e -i '.spec.template.spec.containers[] |= select(.name == "wazuh-indexer").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-indexer:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}"' wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
+          yq e -i '.spec.template.spec.initContainers[] |= select(.name == "init-wazuh-etc").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}"' wazuh/wazuh_managers/wazuh-master-sts.yaml
+          yq e -i '.spec.template.spec.containers[] |= select(.name == "wazuh-manager").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}"' wazuh/wazuh_managers/wazuh-master-sts.yaml
+          yq e -i '.spec.template.spec.initContainers[] |= select(.name == "init-wazuh-etc").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}"' wazuh/wazuh_managers/wazuh-worker-sts.yaml
+          yq e -i '.spec.template.spec.containers[] |= select(.name == "wazuh-manager").image = "${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}"' wazuh/wazuh_managers/wazuh-worker-sts.yaml
 
       - name: Login to AWS ECR
         run: |
@@ -81,21 +209,21 @@ jobs:
 
       - name: Download Wazuh images
         run: |
-          docker pull ${{ env.ECR_REGISTRY }}/wazuh/wazuh-dashboard:${{ env.WAZUH_VERSION }}
-          docker pull ${{ env.ECR_REGISTRY }}/wazuh/wazuh-indexer:${{ env.WAZUH_VERSION }}
-          docker pull ${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}
+          docker pull ${{ env.ECR_REGISTRY }}/wazuh/wazuh-dashboard:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}
+          docker pull ${{ env.ECR_REGISTRY }}/wazuh/wazuh-indexer:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}
+          docker pull ${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}
 
       - name: Load Wazuh images into Minikube
         run: |
-          minikube image load ${{ env.ECR_REGISTRY }}/wazuh/wazuh-dashboard:${{ env.WAZUH_VERSION }}
-          minikube image load ${{ env.ECR_REGISTRY }}/wazuh/wazuh-indexer:${{ env.WAZUH_VERSION }}
-          minikube image load ${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}
+          minikube image load ${{ env.ECR_REGISTRY }}/wazuh/wazuh-dashboard:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}
+          minikube image load ${{ env.ECR_REGISTRY }}/wazuh/wazuh-indexer:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}
+          minikube image load ${{ env.ECR_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}
 
       - name: Download Wazuh certificates tool and config files
         run: |
           cd wazuh/
-          curl -LO "https://packages-dev.wazuh.com/${{ env.WAZUH_MINOR }}/wazuh-certs-tool-${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}.sh"
-          curl -LO "https://packages-dev.wazuh.com/${{ env.WAZUH_MINOR }}/config-${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}.yml"
+          curl -o "wazuh-certs-tool-${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}.sh" "$wazuh_certs_tool"
+          curl -o "config-${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}.yml" "$wazuh_config_yml"
 
       - name: Update config-${{ env.WAZUH_VERSION }}-${{ env.WAZUH_REVISION }}.yml file
         run: |
